---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
  
  
executors:
  node:
    docker:
      - image: cimg/node:16.14
  java:
    docker:
      - image: cimg/openjdk:17.0.3-node
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
#     working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run docker
          command: |
            ./gradlew createDockerfile
      - run:
          name: ls command
          command: |
              ls -lart
      - persist_to_workspace:
          root: ./
          paths:
            - build
workflows:
  my-workflow:
    jobs:
      - build:
      - aws-ecr/build-and-push-image:
          repo: life-pipeline
          dockerfile: build/docker/Dockerfile
          registry-id: AWS_ECR_REGISTRY_ID
          path: .
          requires:
            - "build"

