---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run:
          name: run docker
          command: |
            ./gradlew createDockerfile
      - run:
          name: ls command
          command: |
              ls -lart
      - persist_to_workspace:
          root: ./
          paths:
            - build
workflows:
  my-workflow:
    jobs:
      - build:
           name: "Build docker image"
      - aws-ecr/build-and-push-image:
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_ACCESS_KEY_ID
          dockerfile: ./build/docker
#           registry-id: AWS_ECR_REGISTRY_ID
#           repo: life-pipeline
#           region: eu-west-1
          requires:
            - "Build docker image"

