version: 2.1
        
executors:
  java:
    docker:
      - image: cimg/openjdk:11.0-node
jobs:
  build:
    executor: java
    steps:
      - checkout
      - run:
          name: ls command for jar
          command: |
              ls 
workflows:
  build-test-deploy:
    when:
      and:
        - equal: [main, <<pipeline.git.branch>>]
    jobs:
      - deploy_dev_approval:
          name: "Deploy dev approval"
          type: approval
      - build:
          requires:
            - "Deploy dev approval"
