---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
#     working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: run docker
          command: |
            ./gradlew createDockerfile
      - run:
          name: ls command
          command: |
              ls -lart
      - persist_to_workspace:
          root: ./
          paths:
            - build
workflows:
  my-workflow:
    jobs:
      - build:
           name: "Build"
      - aws-ecr/build-and-push-image:
#           aws-access-key-id: AWS_ACCESS_KEY_ID
#           aws-secret-access-key: AWS_ACCESS_KEY_ID
          dockerfile: build/docker/Dockerfile
          path: .
          repo: life-pipeline
#           region: eu-west-1
          requires:
            - "Build"
