version: 2.1

parameters:
  deploy:
    type: boolean
    default: false
  environment_ecs:
    type: string
    default: ""
  app_version:
    type: string
    default: ""
  run-schedule:
    type: boolean
    default: false
jobs:
  build:
    steps:
      - checkout
      - run:
          name: ls command for jar
          command: |
              ls <<pipeline.parameters.environment_ecs>>
workflows:
  build-test-deploy:
    when:
      and:
        - equal: [main, <<pipeline.git.branch>>]
        - not: << pipeline.parameters.run-schedule >>
    jobs:
      - build

 nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "5 * * * *" # use cron syntax to set the schedule
        filters:
          branches:
            only:
             - master
    jobs:
#       - deploy_dev_approval:
#           name: "Deploy dev approval"
#           type: approval
      - build
          filters:
            branches:
              only:
               - main
#         requires:
#             - "Deploy dev approval"


