version: 2.1

parameters:
  deploy:
    type: boolean
    default: false
  environment_ecs:
    type: string
    default: ""
  app_version:
    type: string
    default: ""
jobs:
  build:
    parameters:
      p:
        type: integer
        default: 1
    parallelism: << parameters.p >>
    machine: true
    steps:
      - checkout
      - run:
          name: ls command for jar
          command: |
              ls <<pipeline.parameters.environment_ecs>>
workflows:
  workflow:
    jobs:
      - build:
          p: 2
          filters:
            branches:
              only:
                - main
